### ISSUE TITLE
Evaluate source selection on SoTA engines

### ISSUE THREAD

**Issue by mhoangvslev** [GDD-Nantes/FedShop#13]
force other source selection from other engines (Hibiscus, ...)

# Tasks:
- [x] Read SoTA
- [x] Evaluate on as many engines as possible

# Reading list:
- [x] [Source Selection for SPARQL Endpoints: Fit for Heterogeneous Federations of RDF Data Sources?](https://ceur-ws.org/Vol-3279/paper1.pdf)
- [x] FedX: Optimization Techniques for Federated Query Processing on Linked Data
- [x] Lusail: A System for Querying Linked Data at Scale
- [x] HiBISCuS: Hypergraph-Based Source Selection for SPARQL Endpoint Federation 
- [x] ADERIS: An Adaptive Query Processor for Joining Federated SPARQL Endpoints
- [x] DARQ: Querying Distributed RDF Data Sources with SPARQL
- [x] The Odyssey Approach for Optimizing Federated SPARQL Queries
- [x] SPLENDID: SPARQL Endpoint Federation Exploiting VOID Descriptions
- [x] SemaGrow: Optimizing Federated SPARQL Queries 
- [x] LHD: Optimising linked data query processing using parallelisation
