### ISSUE TITLE
Scale up the experiment

### ISSUE THREAD

**Issue by mhoangvslev** [GDD-Nantes/FedShop#23]
# Objective:
In the previous iteration, we tried with 3 batches of (3, 6, 9 shops + 1, 2, 3 reviewers).
In this iteration, we aim to test with 10, 20, 30 ... 100 shops. 

# Tasks:
- [ ] Toy dataset with 3 batches of (3, 6, 9 shops + 1, 2, 3 reviewers)
- [ ] Fully implemented BSBM (Issue #10) + 3 batches (10, 20, 30)
- [ ] Fully implemented BSBM (Issue #10) + 10 batches (10, 20, 30 ... 100 shops + reviewers)
